# Bank Custumer Churn
As we know, it is much more expensive to sign in a new client than keeping an existing one.
It is advantageous for banks to know what leads a client towards the decision to leave the company.
Churn prevention allows companies to develop loyalty programs and retention campaigns to keep as many customers as possible.

In business, churn means the rate at which customers stop using a company's product or service or employees leave their jobs over a specific time period. It is commonly tracked as a percentage using metrics like customer churn or revenue churn.

### Importing Essential Liberaries

In [20]:
import pandas as pd
import numpy as np

### Importing and Reading Dataset

In [39]:
raw_data = pd.read_csv("Customer-Churn-Records.csv")

In [41]:
df = raw_data.copy()

In [43]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1,2,DIAMOND,464
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1,3,DIAMOND,456
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1,3,DIAMOND,377
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,5,GOLD,350
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0,5,GOLD,425

- RowNumber: corresponds to the record (row) number and has no effect on the output.
- CustomerId : contains random values and has no effect on customer leaving the bank. 
- Surname : the surname of a customer has no impact on their decision to leave the bank. 
- CreditScore : can have an effect on customer churn, since a customer with a higher credit score is less likely to leave the bank. 
- Geography : a customer’s location can affect their decision to leave the bank. 
- Gender : gender of customers 
- Age : Age of customers
- Tenure : refers to the number of years that the customer has been a client of the bank.
- Balance : balance in their bank accounts. 
- NumOfProducts : refers to the number of products that a customer has purchased through the bank. 
- HasCrCard : denotes whether or not a customer has a credit card.
- IsActiveMember : active customers or not. 
- EstimatedSalary : Monthly customer salaries. 
- Exited : whether or not the customer left the bank. 
- Complain : customer has complaint or not.
- Satisfaction Score : Score provided by the customer for their complaint resolution. 
- Card Type : type of card hold by the customer. Points Earned—the points earned by the customer for using credit card.

### Understanding The Data

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   RowNumber           10000 non-null  int64
 1   CustomerId          10000 non-null  int64
 2   Surname             10000 non-null  object
 3   CreditScore         10000 non-null  int64
 4   Geography           10000 non-null  object
 5   Gender              10000 non-null  object
 6   Age                 10000 non-null  int64
 7   Tenure              10000 non-null  int64
 8   Balance             10000 non-null  float64
 9   NumOfProducts       10000 non-null  int64
 10  HasCrCard           10000 non-null  int64
 11  IsActiveMember      10000 non-null  int64
 12  EstimatedSalary     10000 non-null  float64
 13  Exited              10000 non-null  int64
 14  Complain            10000 non-null  int64
 15  Satisfaction Score  10000 non-null  int64
 16  Card Type           10000 non-null  object
 17  Point Earned        10000 non-null  int64
dtypes: float64(2), int64(12), object(4)
memory usage: 1.4+ MB

In [50]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Point Earned
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203800,0.204400,3.013800,606.515100
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402842,0.403283,1.405919,225.924839
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000,0.000000,1.000000,119.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000,0.000000,2.000000,410.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000,0.000000,3.000000,605.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000,0.000000,4.000000,801.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000,1.000000,5.000000,1000.000000

In [52]:
df.shape

(10000, 18)

### Understanding columns types

In [56]:
num_cols = [feature for feature in df.columns if df[feature].dtype != "object" ]
print(num_cols)

['RowNumber', 'CustomerId', 'CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited', 'Complain', 'Satisfaction Score', 'Point Earned']

In [74]:
category_cols = [feature for feature in df.columns if df[feature].dtype == "object" ]
print(category_cols)

['Surname', 'Geography', 'Gender', 'Card Type']

In [64]:
discrete_num_cols = [feature for feature in df[num_cols] if df[feature].nunique() < 15]
print(discrete_num_cols)

['Tenure', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'Exited', 'Complain', 'Satisfaction Score']

In [82]:
low_cardinality_cols = [feature for feature in df[category_cols] if df[feature].nunique() < 15]
print(low_cardinality_cols)

['Geography', 'Gender', 'Card Type']

#### Value Counts

In [96]:
for i in df[discrete_num_cols]:
    print(df[i].value_counts())
    print("-"*25)

Tenure
2     1048
1     1035
7     1028
8     1025
5     1012
3     1009
4      989
9      984
6      967
10     490
0      413
Name: count, dtype: int64
-------------------------
NumOfProducts
1    5084
2    4590
3     266
4      60
Name: count, dtype: int64
-------------------------
HasCrCard
1    7055
0    2945
Name: count, dtype: int64
-------------------------
IsActiveMember
1    5151
0    4849
Name: count, dtype: int64
-------------------------
Exited
0    7962
1    2038
Name: count, dtype: int64
-------------------------
Complain
0    7956
1    2044
Name: count, dtype: int64
-------------------------
Satisfaction Score
3    2042
2    2014
4    2008
5    2004
1    1932
Name: count, dtype: int64
-------------------------

In [90]:
for i in df[low_cardinality_cols]:
    print(df[i].value_counts())
    print("-"*25)

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64
-------------------------
Gender
Male      5457
Female    4543
Name: count, dtype: int64
-------------------------
Card Type
DIAMOND     2507
GOLD        2502
SILVER      2496
PLATINUM    2495
Name: count, dtype: int64
-------------------------

## Data Learnings
- Satisfaction Score is an ordinal categorical feature. 
- Card Type is low cardinality ordinal Data.
- Data is Mostly clean have no outliers and null values.
- RowNumber, CustomerId, and Surname can be removed as they do not provide useful predictive information.
- low cardinality columns can be converted using label encoding and OneHotEncoding.
- Target Feature will be "Exited" ,where:
  - 0 : Customer Stayed
  - 1 : Customer Churned