## Importing Liberaries

In [20]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import (OneHotEncoder,
                                OrdinalEncoder,
                                StandardScaler,)
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
import pickle

### Importing and Reading dataset

In [23]:
raw = pd.read_csv('Customer-Churn-Records.csv')
df = raw.copy()
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1,2,DIAMOND,464
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1,3,DIAMOND,456
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1,3,DIAMOND,377
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,5,GOLD,350
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0,5,GOLD,425

### Dropping Unnecessary Features

In [25]:
cols_to_drop = ['RowNumber','CustomerId','Surname','Complain']
df.drop(columns=cols_to_drop,inplace=True)

In [27]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Satisfaction Score,Card Type,Point Earned
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1,2,DIAMOND,464
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,3,DIAMOND,456
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,3,DIAMOND,377
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,5,GOLD,350
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,5,GOLD,425

In [29]:
num_cols = ['CreditScore','Age','Balance','EstimatedSalary','Point Earned']
cat_cols = ['Geography','Gender','Tenure','Card Type']
ordinal_cols = ['Satisfaction Score']

### Split the Data into Train and Test

In [32]:
X = df.drop('Exited',axis = 1)
y = df['Exited']

In [34]:
X.shape,y.shape

((10000, 13), (10000,))

In [36]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.25,random_state=12
)

In [38]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((7500, 13), (2500, 13), (7500,), (2500,))

### Columns Transformation

In [41]:
num_pipeline = Pipeline(
    steps = [
        ('scaler',StandardScaler())
    ]
)
cat_pipeline = Pipeline(
    steps = [
        ('OneHotEncoding', OneHotEncoder(drop='first'))
    ]
)
ordinal_pipeline = Pipeline(
    steps = [
        ('OrdinalEncoding',OrdinalEncoder())
    ]
)

In [43]:
preprocessor = ColumnTransformer(
    transformers= [
        ('Numerical',num_pipeline,num_cols),
        ('Categorical',cat_pipeline,cat_cols),
        ('Ordinal',ordinal_pipeline,ordinal_cols)
    ],
    remainder="passthrough"
)

In [45]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

### Saving the Preprocessor File

In [48]:
with open('preprocessor.pkl','wb') as file:
    pickle.dump(preprocessor,file)